#!/usr/bin/env python3
"""
DHSD v2 — Adaptive Dual-Signal Distillation
============================================
Rewrite of train_dhsd.py to fix cross-generator collapse.

KEY CHANGES vs v1
-----------------
1. DROP 22-d semantic regression. It was a Midjourney-specific bottleneck that
   destroyed CLIP's generalizable features. v1 student macro was 0.6527 vs
   zero-shot CLIP 0.8897 — proof the regression was actively harmful.

2. ADAPTIVE per-sample weights on distillation losses:
     w_i = |P_t - 0.5| * 2   if teacher agrees with GT, else 0
   Teacher only teaches when it is both confident AND correct.
   Wrong-and-confident teacher predictions are ignored, not learned.

3. CLIP zero-shot probability as a SECOND teacher. We precompute p_clip once
   for the whole train set using ensemble of real/fake text prompts. Distill
   from this with the same adaptive weighting logic.

4. WARM-UP: 1 epoch CE-only so the classifier head latches onto the task
   before distillation kicks in. Prevents early KD from pulling weights
   toward teacher's bad calibration before student has a clue.

5. SIMPLER head: TIE multi-layer pooling (kept from v1) + MLP classifier.
   No NPR branch, no semantic head, no forced 22-d bottleneck.

6. Monitor cross-gen macro, stop early if it stops improving.
"""
import os, sys, json, time, random, math, numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from pathlib import Path
from PIL import Image
from collections import defaultdict
from torch.utils.data import Dataset, DataLoader
from torch.amp import autocast, GradScaler
from sklearn.metrics import roc_auc_score, accuracy_score
import open_clip

sys.stdout.reconfigure(line_buffering=True)

# ================= CONFIG =================
SEED         = 42
DEVICE       = "cuda"
HF_CACHE     = "/NAS_DISK/Saptarshi_data/hf_cache"
DATA_ROOT    = Path("/NAS_DISK/Saptarshi_data/dataset")
CNN_ROOT     = DATA_ROOT / "cnndetection_test"

TEACHER_PROB = "/NAS_DISK/Saptarshi_data/hybrid_teacher_soft_labels.npz"
# Schema: keys = {'ids', 'probs', 'labels'}
#   ids:    (N,)   str, e.g. 'img000008'
#   probs:  (N, 2) float32, columns = [P_real, P_fake]
#   labels: (N,)   int, 0=real, 1=fake

OUT_DIR = Path(f"/NAS_DISK/Saptarshi_data/dhsd_v2_{time.strftime('%Y%m%d_%H%M%S')}")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Training
EPOCHS         = 15
BATCH_SIZE     = 96
LR             = 1.5e-4
WEIGHT_DECAY   = 1e-4
PATIENCE       = 5
WARMUP_EPOCHS  = 2

# Loss weights
ALPHA_TEACHER  = 0.5    # adaptive teacher KD
BETA_CLIP      = 1.5    # adaptive CLIP-zero-shot KD
TEMP           = 4.0    # distillation temperature

# CLIP zero-shot prompts
REAL_PROMPTS = [
    "a real photograph",
    "a photograph taken with a camera",
    "an authentic photo of a real scene",
    "a natural unedited photograph",
]
FAKE_PROMPTS = [
    "an AI-generated image",
    "a synthetic image generated by a neural network",
    "a computer-generated image",
    "a fake image generated by a diffusion model",
]

# Reproducibility
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.benchmark = True

# ================= DATA =================
class ImgDataset(Dataset):
    """
    Returns (image_tensor, label, sample_id).
    - Training images come from Midjourney + COCO.
    - sample_id is the filename stem used to key into teacher feats/probs.
    """
    def __init__(self, items, preprocess, augment=False):
        self.items = items
        self.preprocess = preprocess
        self.augment = augment

    def __len__(self):
        return len(self.items)

    def _aug(self, img):
        # Safe augmentations only — no resize, no flip for faces
        if random.random() < 0.5:
            # JPEG compression
            import io
            buf = io.BytesIO()
            q = random.randint(60, 95)
            img.save(buf, format="JPEG", quality=q)
            buf.seek(0)
            img = Image.open(buf).convert("RGB")
        if random.random() < 0.3:
            from PIL import ImageFilter
            img = img.filter(ImageFilter.GaussianBlur(radius=random.uniform(0.1, 1.5)))
        return img

    def __getitem__(self, i):
        path, label, sid = self.items[i]
        img = Image.open(path).convert("RGB")
        if self.augment:
            img = self._aug(img)
        x = self.preprocess(img)
        return x, torch.tensor(label, dtype=torch.float32), sid


def build_train_items():
    """
    Scans Midjourney (fake=1) and COCO (real=0), returns list of (path, label, id).
    Adjust paths if your layout differs.
    """
    items = []
    mj_dir = DATA_ROOT / "fake" / "midjourney"
    co_dir = DATA_ROOT / "real" / "coco"
    for d, lbl in [(mj_dir, 1), (co_dir, 0)]:
        for p in sorted(d.glob("*")):
            if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}:
                items.append((str(p), lbl, p.stem))
    random.shuffle(items)
    return items


def build_cnn_splits():
    """
    For each generator subfolder under cnndetection_test/, yield (name, val_items, test_items).
    Handles both layouts transparently:
      Flat:   gen/0_real/*.png          gen/1_fake/*.png
      Nested: gen/class/0_real/*.png    gen/class/1_fake/*.png
    Groups images by whether '0_real' or '1_fake' appears anywhere in the path.
    """
    splits = {}
    if not CNN_ROOT.exists():
        print(f"  [warn] CNN test root missing: {CNN_ROOT}")
        return splits
    exts = {".jpg", ".jpeg", ".png", ".webp"}
    for gen_dir in sorted(CNN_ROOT.iterdir()):
        if not gen_dir.is_dir():
            continue
        if gen_dir.name.startswith("."):
            continue
        name = gen_dir.name

        real_imgs, fake_imgs = [], []
        for p in gen_dir.rglob("*"):
            if not p.is_file():
                continue
            if p.suffix.lower() not in exts:
                continue
            parts = set(p.parts)
            if "0_real" in parts:
                real_imgs.append((str(p), 0))
            elif "1_fake" in parts:
                fake_imgs.append((str(p), 1))

        if not real_imgs or not fake_imgs:
            print(f"  [skip] {name}: real={len(real_imgs)}  fake={len(fake_imgs)} (missing class)")
            continue

        all_imgs = real_imgs + fake_imgs
        random.Random(SEED).shuffle(all_imgs)
        val_k = min(500, len(all_imgs) // 5)
        val_items = all_imgs[:val_k]
        test_items = all_imgs[val_k:]
        splits[name] = (val_items, test_items)
    return splits


# ================= CLIP BACKBONE =================
_tap_buffer = {}

def make_hook(idx):
    def hook(module, inp, out):
        # open_clip ViT-L/14 resblocks: (T=257, B, D=1024). CLS at T=0.
        if out.dim() == 3:
            if out.shape[0] == 257:
                cls = out[0]              # (B, 1024)
            elif out.shape[1] == 257:
                cls = out[:, 0]           # (B, 1024)
            else:
                cls = out[0]              # assume (T, B, D)
        else:
            cls = out
        _tap_buffer[idx] = cls
    return hook


def load_clip():
    model, _, preprocess = open_clip.create_model_and_transforms(
        "ViT-L-14", pretrained="openai", cache_dir=HF_CACHE
    )
    tokenizer = open_clip.get_tokenizer("ViT-L-14")
    model = model.to(DEVICE).eval()
    for p in model.parameters():
        p.requires_grad = False

    # Hook intermediate resblocks
    tap_blocks = [6, 12, 18, 24]
    handles = []
    for i, bi in enumerate(tap_blocks):
        blk = model.visual.transformer.resblocks[bi - 1]
        h = blk.register_forward_hook(make_hook(i))
        handles.append(h)
    return model, preprocess, tokenizer, tap_blocks


@torch.no_grad()
def clip_forward(model, x):
    """Run CLIP, return (final_cls (B,768), taps list of (B,1024))."""
    _tap_buffer.clear()
    feat = model.encode_image(x)                       # (B, 768)
    taps = [_tap_buffer[i] for i in range(4)]
    return feat, taps


@torch.no_grad()
def precompute_clip_zeroshot_probs(model, tokenizer, loader):
    """
    Returns dict: sample_id -> p_fake (float)
    Uses ensemble of real/fake text prompts via cosine similarity.
    """
    real_tok = tokenizer(REAL_PROMPTS).to(DEVICE)
    fake_tok = tokenizer(FAKE_PROMPTS).to(DEVICE)
    tr = model.encode_text(real_tok); tr = tr / tr.norm(dim=-1, keepdim=True)
    tf = model.encode_text(fake_tok); tf = tf / tf.norm(dim=-1, keepdim=True)
    real_proto = tr.mean(0); real_proto = real_proto / real_proto.norm()
    fake_proto = tf.mean(0); fake_proto = fake_proto / fake_proto.norm()

    out = {}
    print("  computing CLIP zero-shot probs over train set...")
    for bi, (x, y, sids) in enumerate(loader):
        x = x.to(DEVICE, non_blocking=True)
        f, _ = clip_forward(model, x)
        f = f / f.norm(dim=-1, keepdim=True)
        sim_r = f @ real_proto
        sim_f = f @ fake_proto
        # Temperature-scaled logit; calibrated loosely
        logit = (sim_f - sim_r) * 100.0
        p = torch.sigmoid(logit).cpu().numpy()
        for pid, sid in enumerate(sids):
            out[sid] = float(p[pid])
        if bi % 20 == 0:
            print(f"    {bi}/{len(loader)}")
    return out


# ================= STUDENT HEAD =================
class TIE(nn.Module):
    """
    Trainable Importance Estimator from RINE.
    Projects each tap CLS (B, D_in) -> (B, D_out), then softmax-attends across K taps.
    """
    def __init__(self, n_taps, d_in, d_out):
        super().__init__()
        self.proj = nn.ModuleList([nn.Linear(d_in, d_out) for _ in range(n_taps)])
        self.attn = nn.Sequential(
            nn.Linear(d_out, d_out // 2), nn.GELU(),
            nn.Linear(d_out // 2, 1),
        )

    def forward(self, taps):
        # taps: list of (B, D_in), length K
        proj = torch.stack([F.gelu(self.proj[i](t)) for i, t in enumerate(taps)], dim=1)  # (B, K, D_out)
        w = self.attn(proj)                  # (B, K, 1)
        w = F.softmax(w, dim=1)
        pooled = (proj * w).sum(dim=1)       # (B, D_out)
        return F.normalize(pooled, dim=-1)


class DHSDv2(nn.Module):
    """
    Lean student: TIE over 4 intermediate CLS tokens + final CLIP feat -> MLP -> logit.
    No semantic head, no NPR.
    """
    def __init__(self, n_taps=4, d_tap=1024, d_final=768, d_hidden=256):
        super().__init__()
        self.tie = TIE(n_taps=n_taps, d_in=d_tap, d_out=128)
        self.final_proj = nn.Sequential(
            nn.Linear(d_final, 128), nn.GELU(),
        )
        self.classifier = nn.Sequential(
            nn.Linear(256, d_hidden), nn.GELU(), nn.Dropout(0.2),
            nn.Linear(d_hidden, 64), nn.GELU(), nn.Dropout(0.1),
            nn.Linear(64, 1),
        )

    def forward(self, final_cls, taps):
        tie_feat = self.tie(taps)                            # (B, 128)
        fin_feat = F.normalize(self.final_proj(final_cls), dim=-1)  # (B, 128)
        combined = torch.cat([tie_feat, fin_feat], dim=-1)  # (B, 256)
        logit = self.classifier(combined).squeeze(-1)       # (B,)
        return logit, combined


# ================= ADAPTIVE LOSS =================
def adaptive_weight(p_teacher, y):
    """
    w_i = |p - 0.5| * 2  if sign(p - 0.5) == sign(y - 0.5), else 0
    p_teacher: (B,) in [0, 1]
    y        : (B,) in {0, 1}
    """
    pred_hard = (p_teacher > 0.5).float()
    agree = (pred_hard == y).float()
    conf = (p_teacher - 0.5).abs() * 2.0     # in [0, 1]
    return conf * agree


def kd_loss(student_logit, teacher_prob, temp=TEMP):
    """
    KL(student || teacher) with temperature, per-sample.
    Returns (B,) vector.
    """
    # Convert teacher prob -> soft logit
    eps = 1e-6
    p = teacher_prob.clamp(eps, 1 - eps)
    teacher_logit = torch.log(p / (1 - p))

    # Temperature-scale both, convert to [prob_class0, prob_class1]
    s = student_logit / temp
    t = teacher_logit / temp
    s2 = torch.stack([-s, s], dim=-1)   # (B, 2) logits
    t2 = torch.stack([-t, t], dim=-1)

    log_s = F.log_softmax(s2, dim=-1)
    soft_t = F.softmax(t2, dim=-1)
    kl = F.kl_div(log_s, soft_t, reduction="none").sum(dim=-1)  # (B,)
    return kl * (temp ** 2)


# ================= EVAL =================
@torch.no_grad()
def eval_loader(clip_model, head, loader, tag=""):
    head.eval()
    all_p, all_y = [], []
    for x, y, _ in loader:
        x = x.to(DEVICE, non_blocking=True)
        feat, taps = clip_forward(clip_model, x)
        logit, _ = head(feat, taps)
        p = torch.sigmoid(logit).cpu().numpy()
        all_p.append(p); all_y.append(y.numpy())
    all_p = np.concatenate(all_p); all_y = np.concatenate(all_y)
    try:
        auroc = roc_auc_score(all_y, all_p)
    except ValueError:
        auroc = float("nan")
    acc = accuracy_score(all_y, (all_p > 0.5).astype(int))
    return auroc, acc, all_p, all_y


# ================= MAIN =================
def main():
    print("=" * 70)
    print("DHSD v2 — Adaptive Dual-Signal Distillation")
    print(f"Output: {OUT_DIR}")
    print("=" * 70)

    # -- 1. CLIP
    print("\n[1/7] Loading CLIP ViT-L/14 (frozen) + intermediate hooks...")
    clip_model, preprocess, tokenizer, tap_blocks = load_clip()
    print(f"  Hooks registered on blocks {tap_blocks}")

    # -- 2. Teacher artifacts
    print("\n[2/7] Loading teacher P(fake) probabilities...")
    tprob_npz = np.load(TEACHER_PROB, allow_pickle=True)
    t_ids   = tprob_npz["ids"]
    t_probs = tprob_npz["probs"]
    # hybrid file stores probs as (N, 2) = [P_real, P_fake]. Take col 1.
    if t_probs.ndim == 2:
        t_probs = t_probs[:, 1]
    teacher_prob_map = dict(zip(t_ids, t_probs.astype(np.float32)))
    print(f"  {len(teacher_prob_map)} images with teacher probs "
          f"(P_fake range: {float(t_probs.min()):.3f} – {float(t_probs.max()):.3f}, "
          f"mean: {float(t_probs.mean()):.3f})")

    # -- 3. Datasets
    print("\n[3/7] Building datasets...")
    all_items = build_train_items()
    # Keep only items for which we have teacher probs
    all_items = [it for it in all_items if it[2] in teacher_prob_map]
    random.Random(SEED).shuffle(all_items)
    n_test = int(len(all_items) * 0.15)
    n_val  = int(len(all_items) * 0.15)
    mj_test_items  = all_items[:n_test]
    mj_val_items   = all_items[n_test:n_test + n_val]
    train_items    = all_items[n_test + n_val:]
    print(f"  Train: {len(train_items):,}   MJ val: {len(mj_val_items):,}   MJ test: {len(mj_test_items):,}")

    train_ds = ImgDataset(train_items, preprocess, augment=True)
    mj_val_ds = ImgDataset(mj_val_items, preprocess, augment=False)
    mj_test_ds = ImgDataset(mj_test_items, preprocess, augment=False)

    nw = 6
    train_loader   = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=nw, pin_memory=True, drop_last=True)
    mj_val_loader  = DataLoader(mj_val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=nw, pin_memory=True)
    mj_test_loader = DataLoader(mj_test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=nw, pin_memory=True)

    # -- 4. CNN splits
    print("\n[4/7] Loading CNNDetection cross-gen splits...")
    cnn_splits = build_cnn_splits()
    cnn_val_loaders = {}
    cnn_test_loaders = {}
    for name, (vi, ti) in cnn_splits.items():
        vds = ImgDataset([(p, l, Path(p).stem) for p, l in vi], preprocess, augment=False)
        tds = ImgDataset([(p, l, Path(p).stem) for p, l in ti], preprocess, augment=False)
        cnn_val_loaders[name]  = DataLoader(vds, batch_size=BATCH_SIZE, shuffle=False, num_workers=nw, pin_memory=True)
        cnn_test_loaders[name] = DataLoader(tds, batch_size=BATCH_SIZE, shuffle=False, num_workers=nw, pin_memory=True)
        print(f"  {name:<22}  val={len(vi):>5}  test={len(ti):>6}")

    # -- 5. Precompute CLIP zero-shot probs on training set
    print("\n[5/7] Precomputing CLIP zero-shot P(fake) for training samples...")
    # Use a non-augmented pass
    precomp_ds = ImgDataset(train_items, preprocess, augment=False)
    precomp_loader = DataLoader(precomp_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=nw, pin_memory=True)
    clip_zs_map = precompute_clip_zeroshot_probs(clip_model, tokenizer, precomp_loader)
    # Sanity: check agreement with GT
    zs_preds = np.array([clip_zs_map[sid] for _, _, sid in train_items])
    zs_labels = np.array([lbl for _, lbl, _ in train_items])
    zs_auroc = roc_auc_score(zs_labels, zs_preds)
    zs_agree = ((zs_preds > 0.5) == (zs_labels > 0.5)).mean()
    print(f"  CLIP zero-shot on train: AUROC={zs_auroc:.4f}  hard-agree={zs_agree:.3f}")

    # Sanity for teacher
    tp_preds = np.array([teacher_prob_map[sid] for _, _, sid in train_items])
    tp_auroc = roc_auc_score(zs_labels, tp_preds)
    tp_agree = ((tp_preds > 0.5) == (zs_labels > 0.5)).mean()
    print(f"  Teacher       on train: AUROC={tp_auroc:.4f}  hard-agree={tp_agree:.3f}")

    # -- 6. Build head
    print("\n[6/7] Building DHSD v2 head...")
    head = DHSDv2().to(DEVICE)
    n_params = sum(p.numel() for p in head.parameters() if p.requires_grad)
    print(f"  Trainable parameters: {n_params / 1e6:.2f}M")

    optimizer = torch.optim.AdamW(head.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    total_steps = EPOCHS * len(train_loader)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer, max_lr=LR, total_steps=total_steps,
        pct_start=0.1, anneal_strategy="cos", div_factor=25, final_div_factor=1e3,
    )
    scaler = GradScaler(device=DEVICE)

    # -- 7. Train
    print("\n[7/7] Training...")
    best = {"crossgen_macro": -1.0, "epoch": -1}
    no_improve = 0

    for epoch in range(EPOCHS):
        head.train()
        ep_start = time.time()
        ep_stats = defaultdict(float); n_batches = 0
        kd_on = epoch >= WARMUP_EPOCHS

        for bi, (x, y, sids) in enumerate(train_loader):
            x = x.to(DEVICE, non_blocking=True)
            y = y.to(DEVICE, non_blocking=True)

            # Lookup teacher + CLIP-zs probs
            p_t = torch.tensor([teacher_prob_map[s] for s in sids], device=DEVICE)
            p_c = torch.tensor([clip_zs_map[s] for s in sids], device=DEVICE)

            optimizer.zero_grad()
            with autocast(device_type="cuda", dtype=torch.bfloat16):
                with torch.no_grad():
                    feat, taps = clip_forward(clip_model, x)
                logit, _ = head(feat, taps)

                # Task loss
                bce = F.binary_cross_entropy_with_logits(logit, y)

                # Adaptive KD losses (per-sample weighted)
                if kd_on:
                    w_t = adaptive_weight(p_t, y)
                    w_c = adaptive_weight(p_c, y)
                    kd_t_vec = kd_loss(logit, p_t, temp=TEMP)
                    kd_c_vec = kd_loss(logit, p_c, temp=TEMP)
                    # Normalize by sum of weights to keep scale stable
                    kd_t = (w_t * kd_t_vec).sum() / (w_t.sum() + 1e-6)
                    kd_c = (w_c * kd_c_vec).sum() / (w_c.sum() + 1e-6)
                else:
                    kd_t = torch.tensor(0.0, device=DEVICE)
                    kd_c = torch.tensor(0.0, device=DEVICE)

                loss = bce + ALPHA_TEACHER * kd_t + BETA_CLIP * kd_c

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(head.parameters(), max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            ep_stats["loss"] += loss.item()
            ep_stats["bce"]  += bce.item()
            ep_stats["kd_t"] += kd_t.item() if kd_on else 0.0
            ep_stats["kd_c"] += kd_c.item() if kd_on else 0.0
            n_batches += 1

            if bi % 50 == 0:
                lr = scheduler.get_last_lr()[0]
                tag = "KD" if kd_on else "WARMUP"
                print(f"  ep{epoch:02d} [{bi:>4}/{len(train_loader)}] [{tag}] "
                      f"L={loss.item():.3f} BCE={bce.item():.3f} "
                      f"KD_t={kd_t.item():.3f} KD_c={kd_c.item():.3f} lr={lr:.2e}")

        # --- Eval ---
        for k in ep_stats: ep_stats[k] /= n_batches
        mj_val_auroc, _, _, _ = eval_loader(clip_model, head, mj_val_loader, "mj_val")

        per_gen_val = {}
        for name, loader in cnn_val_loaders.items():
            auroc, _, _, _ = eval_loader(clip_model, head, loader, name)
            per_gen_val[name] = auroc
        crossgen_macro = float(np.nanmean(list(per_gen_val.values())))

        dt = time.time() - ep_start
        print(f"\n[ep {epoch:02d}] loss={ep_stats['loss']:.4f}  "
              f"MJ_val={mj_val_auroc:.4f}  CROSSGEN_MACRO={crossgen_macro:.4f}  "
              f"time={dt:.0f}s")
        for name, a in sorted(per_gen_val.items()):
            print(f"    {name:<22}  val_AUROC={a:.4f}")

        # Save ckpt
        ck_path = OUT_DIR / f"ep{epoch:02d}.pt"
        torch.save({
            "state": head.state_dict(),
            "epoch": epoch,
            "crossgen_macro": crossgen_macro,
            "mj_val": mj_val_auroc,
            "per_gen_val": per_gen_val,
        }, ck_path)

        if crossgen_macro > best["crossgen_macro"]:
            best.update({
                "crossgen_macro": crossgen_macro,
                "epoch": epoch,
                "path": str(ck_path),
                "per_gen_val": per_gen_val,
                "mj_val": mj_val_auroc,
            })
            torch.save({"state": head.state_dict(), **best}, OUT_DIR / "best.pt")
            print(f"  ✓ new best crossgen_macro={crossgen_macro:.4f} saved")
            no_improve = 0
        else:
            no_improve += 1
            print(f"  no improvement ({no_improve}/{PATIENCE}) "
                  f"best={best['crossgen_macro']:.4f}@{best['epoch']}")
            if no_improve >= PATIENCE:
                print(f"\n  Early stop at epoch {epoch}")
                break

    # --- FINAL TEST EVAL on best ckpt ---
    print(f"\n[FINAL] Loading best (ep{best['epoch']}, crossgen_val_macro={best['crossgen_macro']:.4f})")
    head.load_state_dict(torch.load(OUT_DIR / "best.pt")["state"])
    head.eval()

    mj_auroc, mj_acc, _, _ = eval_loader(clip_model, head, mj_test_loader, "mj_test")
    print(f"MJ test AUROC: {mj_auroc:.4f}  acc={mj_acc:.4f}")

    print("\nCrossgen-TEST evaluation:")
    test_results = {}
    for name, loader in cnn_test_loaders.items():
        auroc, acc, _, _ = eval_loader(clip_model, head, loader, name)
        test_results[name] = {"auroc": auroc, "acc": acc, "n": len(loader.dataset)}
        marker = "✓" if auroc >= 0.80 else ("~" if auroc >= 0.65 else "✗")
        print(f"  {marker} {name:<22}  n={len(loader.dataset):>6,}  AUROC={auroc:.4f}  acc={acc:.4f}")

    macro = float(np.nanmean([r["auroc"] for r in test_results.values()]))
    print("\n" + "=" * 70)
    print("DHSD v2 FINAL")
    print("=" * 70)
    print(f"  Trainable params : {n_params/1e6:.2f}M")
    print(f"  Best epoch       : {best['epoch']}")
    print(f"  Crossgen VAL macro: {best['crossgen_macro']:.4f}")
    print(f"  MJ test AUROC    : {mj_auroc:.4f}")
    print(f"  Crossgen TEST macro: {macro:.4f}")
    print(f"  Generators ≥ 0.80: {sum(1 for r in test_results.values() if r['auroc'] >= 0.80)}/{len(test_results)}")
    print(f"  Output dir       : {OUT_DIR}")

    # Dump JSON
    with open(OUT_DIR / "final_results.json", "w") as f:
        json.dump({
            "best_epoch": best["epoch"],
            "crossgen_val_macro": best["crossgen_macro"],
            "mj_test_auroc": mj_auroc,
            "crossgen_test_macro": macro,
            "per_gen_test": test_results,
            "per_gen_val_best": best.get("per_gen_val", {}),
            "config": {
                "epochs": EPOCHS, "batch_size": BATCH_SIZE, "lr": LR,
                "wd": WEIGHT_DECAY, "alpha_teacher": ALPHA_TEACHER,
                "beta_clip": BETA_CLIP, "temp": TEMP, "warmup": WARMUP_EPOCHS,
            },
        }, f, indent=2)
    print(f"  Wrote: {OUT_DIR / 'final_results.json'}")


if __name__ == "__main__":
    main()
