"""
CLIP Utilities for SPARK-AF
===========================
Text prototype classifier, visual projection, and pseudo-labeling
for Annotation-Free Class-Incremental Learning.

Architecture:
    Image → timm ViT-B/16 CLIP (768-dim, frozen) → SPARK prompts → CLS (768)
          → frozen projection (768→512) → cosine sim with text prototypes (512)

The CLIPTextClassifier replaces CosineClassifier when using CLIP backbones.
It classifies by cosine similarity between projected visual features and
frozen text prototypes encoded from class names.

All parameters (projection, text prototypes, logit_scale) are frozen.
Only SPARK's prompts are trainable.

Usage:
    from clip_utils import CLIPTextClassifier

    classifier = CLIPTextClassifier(
        class_names=["apple", "baby", "bear", ...],
        clip_model_name="ViT-B-16",
        pretrained="openai",
    )
    logits = classifier(features_768)  # [B, num_classes]
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from typing import List


class CLIPTextClassifier(nn.Module):
    """
    Frozen text prototype classifier using CLIP text encoder.

    Replaces CosineClassifier for CLIP-backbone SPARK. The classifier is
    entirely frozen — prompts are the only trainable parameters.

    Pipeline:
        1. Project 768-dim ViT features → 512-dim CLIP joint space (frozen linear)
        2. L2-normalize projected features
        3. Cosine similarity with frozen text prototypes
        4. Scale by CLIP logit_scale (~100)
    """

    def __init__(
        self,
        class_names: List[str],
        clip_model_name: str = "ViT-B-16",
        pretrained: str = "openai",
        prompt_template: str = "a photo of a {}.",
    ):
        super().__init__()

        import open_clip

        self.num_classes = len(class_names)
        self.class_names = list(class_names)

        # Load CLIP model temporarily — extract what we need, then discard
        clip_model, _, _ = open_clip.create_model_and_transforms(
            clip_model_name, pretrained=pretrained
        )
        clip_model.eval()

        # 1) Logit scale (OpenAI CLIP default: exp(4.6052) ≈ 100)
        logit_scale = clip_model.logit_scale.exp().item()
        self.register_buffer("logit_scale", torch.tensor(logit_scale))

        # 2) Visual projection matrix: 768 → 512 (frozen)
        self.register_buffer("visual_proj", clip_model.visual.proj.clone())
        self.proj_dim = self.visual_proj.shape[1]  # 512

        # 3) Encode class names into text prototypes
        tokenizer = open_clip.get_tokenizer(clip_model_name)
        text_prompts = [
            prompt_template.format(name.replace("_", " ")) for name in class_names
        ]
        tokens = tokenizer(text_prompts)

        with torch.no_grad():
            text_features = clip_model.encode_text(tokens)
            text_features = F.normalize(text_features, p=2, dim=-1)

        self.register_buffer("text_prototypes", text_features)  # [num_classes, 512]

        # Sanity checks
        assert self.visual_proj.shape == (768, self.proj_dim)
        assert self.text_prototypes.shape == (self.num_classes, self.proj_dim)

        # Clean up the full CLIP model — we only keep proj + prototypes + scale
        del clip_model, tokenizer

        print(
            f"[CLIPTextClassifier] {self.num_classes} classes, "
            f"proj 768→{self.proj_dim}, logit_scale={logit_scale:.1f}"
        )

    def project_features(self, features: torch.Tensor) -> torch.Tensor:
        """Project 768-dim ViT features to 512-dim CLIP joint space."""
        return features @ self.visual_proj  # [B, 768] @ [768, 512] → [B, 512]

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        """
        Classify by cosine similarity with text prototypes.

        Args:
            features: [B, 768] ViT CLS features (pre-projection)

        Returns:
            logits: [B, num_classes] scaled cosine similarities
        """
        projected = self.project_features(features)
        projected_norm = F.normalize(projected, p=2, dim=-1)
        logits = projected_norm @ self.text_prototypes.T * self.logit_scale
        return logits

    @property
    def feature_dim(self):
        """Input feature dimension (for compatibility)."""
        return 768

    @property
    def weight(self):
        """Prototype weights (for compatibility with CosineClassifier interface)."""
        return self.text_prototypes


class PseudoLabeledDataset(Dataset):
    """
    Wrapper that replaces original labels with pseudo-labels.

    Used for Annotation-Free CIL: the underlying dataset returns
    (image, original_label), but we override the label with
    a pseudo-label generated by CLIP text prototype matching.
    """

    def __init__(self, base_dataset, pseudo_labels: torch.Tensor):
        self.base = base_dataset
        self.pseudo_labels = pseudo_labels
        assert len(pseudo_labels) == len(base_dataset), (
            f"Pseudo-label count ({len(pseudo_labels)}) != "
            f"dataset size ({len(base_dataset)})"
        )

    def __len__(self):
        return len(self.base)

    def __getitem__(self, idx):
        image, _ = self.base[idx]  # discard original label
        return image, int(self.pseudo_labels[idx])