#!/usr/bin/env python3
"""CLIP Scoring — Full Pipeline for all 21K images"""

import os, json, time, pickle
import numpy as np
import torch
from pathlib import Path
from datetime import datetime
from PIL import Image
from tqdm import tqdm

os.environ["HF_HOME"] = "/NAS_DISK/Saptarshi_data/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/NAS_DISK/Saptarshi_data/hf_cache"

import open_clip
import h5py
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

DATASET_BASE = "/NAS_DISK/Saptarshi_data/dataset"
OUTPUT_DIR   = "/NAS_DISK/Saptarshi_data"
CLIP_MODEL   = "ViT-B-32"
CLIP_PRETRAINED = "openai"

REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "an authentic natural photograph",
    "a genuine real-world photo",
    "a photo captured in the real world",
    "a natural photograph with realistic details",
    "an unedited authentic photograph",
    "a real image with natural lighting and textures",
]

FAKE_PROMPTS = [
    "an AI-generated synthetic image",
    "a fake image created by artificial intelligence",
    "a computer-generated artificial image",
    "an image with AI artifacts and inconsistencies",
    "a synthetic image generated by a neural network",
    "a fake AI-created picture with unnatural elements",
    "an artificially generated image with telltale signs",
]

def load_images():
    imgs = []
    for label, subdir in [("real", "real/coco"), ("fake", "fake/midjourney")]:
        d = Path(DATASET_BASE) / subdir
        for p in sorted(d.glob("*")):
            if p.suffix.lower() in (".jpg", ".jpeg", ".png", ".webp"):
                imgs.append({"path": str(p), "id": p.stem, "ground_truth": label})
    real_n = sum(1 for i in imgs if i["ground_truth"] == "real")
    fake_n = sum(1 for i in imgs if i["ground_truth"] == "fake")
    print(f"Found {len(imgs)} images ({real_n} real, {fake_n} fake)")
    return imgs

def main():
    print("=" * 60)
    print("  CLIP Full Pipeline — All Images")
    print(f"  {datetime.now()}")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    print(f"\nLoading CLIP {CLIP_MODEL}...")
    model, _, preprocess = open_clip.create_model_and_transforms(
        CLIP_MODEL, pretrained=CLIP_PRETRAINED, device=device
    )
    tokenizer = open_clip.get_tokenizer(CLIP_MODEL)
    model.eval()
    print("CLIP loaded!")

    print("Encoding text prompts...")
    with torch.no_grad():
        real_tokens = tokenizer(REAL_PROMPTS).to(device)
        fake_tokens = tokenizer(FAKE_PROMPTS).to(device)
        real_text_feats = model.encode_text(real_tokens)
        fake_text_feats = model.encode_text(fake_tokens)
        real_text_feats = real_text_feats / real_text_feats.norm(dim=-1, keepdim=True)
        fake_text_feats = fake_text_feats / fake_text_feats.norm(dim=-1, keepdim=True)
        real_text_avg = real_text_feats.mean(dim=0, keepdim=True)
        real_text_avg = real_text_avg / real_text_avg.norm(dim=-1, keepdim=True)
        fake_text_avg = fake_text_feats.mean(dim=0, keepdim=True)
        fake_text_avg = fake_text_avg / fake_text_avg.norm(dim=-1, keepdim=True)

    images = load_images()
    total = len(images)

    all_scores = []
    all_completed = []
    all_embeddings = []
    all_image_ids = []
    all_labels = []
    errors = 0
    correct_zeroshot = 0
    t0 = time.time()

    print(f"\nScoring {total} images...")
    for i, img_info in enumerate(tqdm(images, desc="CLIP scoring")):
        try:
            img = preprocess(Image.open(img_info["path"]).convert("RGB")).unsqueeze(0).to(device)

            with torch.no_grad():
                img_feat = model.encode_image(img)
                img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)

                real_sim = (img_feat @ real_text_avg.T).item()
                fake_sim = (img_feat @ fake_text_avg.T).item()

                logits = torch.tensor([real_sim, fake_sim])
                probs = torch.softmax(logits * 100, dim=0)
                real_prob = probs[0].item()
                fake_prob = probs[1].item()

            clip_pred = "fake" if fake_sim > real_sim else "real"
            if clip_pred == img_info["ground_truth"]:
                correct_zeroshot += 1

            label = 1 if img_info["ground_truth"] == "fake" else 0

            all_scores.append({
                "real_similarity": real_sim,
                "fake_similarity": fake_sim,
                "real_probability": real_prob,
                "fake_probability": fake_prob,
                "clip_prediction": clip_pred,
                "image_id": img_info["id"],
                "ground_truth": img_info["ground_truth"],
            })
            all_completed.append(img_info["id"])
            all_embeddings.append(img_feat.cpu().numpy().astype(np.float16).squeeze(0))
            all_image_ids.append(img_info["id"])
            all_labels.append(label)

        except Exception as e:
            errors += 1
            if errors < 10:
                print(f"\nError {img_info['id']}: {e}")
            continue

        if (i + 1) % 2000 == 0:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed
            eta = (total - i - 1) / rate
            print(f"\n  [{i+1}/{total}] {rate:.1f} img/s | ETA: {eta/60:.1f}m | Errors: {errors}")
            progress = {"completed": all_completed, "scores": all_scores, "saved_at": datetime.now().isoformat()}
            with open(os.path.join(OUTPUT_DIR, "clip_progress.json"), "w") as f:
                json.dump(progress, f)

    elapsed = time.time() - t0
    n_scored = len(all_scores)
    zero_shot_acc = correct_zeroshot / n_scored if n_scored > 0 else 0
    n_real = sum(1 for s in all_scores if s["ground_truth"] == "real")
    n_fake = sum(1 for s in all_scores if s["ground_truth"] == "fake")

    print(f"\nScoring done! {n_scored} images in {elapsed/60:.1f}m")
    print(f"Zero-shot accuracy: {zero_shot_acc:.4f}")

    embeddings = np.array(all_embeddings, dtype=np.float16)
    labels = np.array(all_labels, dtype=np.int8)

    print("Training LogisticRegression classifier...")
    X_train, X_test, y_train, y_test = train_test_split(
        embeddings.astype(np.float32), labels, test_size=0.2, random_state=42, stratify=labels
    )
    clf = LogisticRegression(max_iter=1000, random_state=42)
    clf.fit(X_train, y_train)
    clf_acc = accuracy_score(y_test, clf.predict(X_test))
    print(f"Classifier accuracy: {clf_acc:.4f}")

    # === SAVE ALL 7 FILES ===

    print("\nSaving all files...")

    with open(os.path.join(OUTPUT_DIR, "clip_scores.json"), "w") as f:
        json.dump({"metadata": {"created_at": datetime.now().isoformat(), "total": n_scored, "accuracy": clf_acc, "prompts": {"real": REAL_PROMPTS, "fake": FAKE_PROMPTS}}, "scores": all_scores}, f)

    with open(os.path.join(OUTPUT_DIR, "clip_progress.json"), "w") as f:
        json.dump({"completed": all_completed, "scores": all_scores, "saved_at": datetime.now().isoformat()}, f)

    with open(os.path.join(OUTPUT_DIR, "clip_analysis_results.json"), "w") as f:
        json.dump({"metadata": {"created_at": datetime.now().isoformat(), "total": n_scored, "zero_shot_acc": zero_shot_acc, "clf_acc": clf_acc, "model": "ViT-B/32"}, "statistics": {"real": n_real, "fake": n_fake, "correct": correct_zeroshot}, "prompts": {"real": REAL_PROMPTS, "fake": FAKE_PROMPTS}, "scores": all_scores}, f)

    with open(os.path.join(OUTPUT_DIR, "clip_classifier.pkl"), "wb") as f:
        pickle.dump(clf, f)

    max_id_len = max(len(s.encode("utf-8")) for s in all_image_ids)
    with h5py.File(os.path.join(OUTPUT_DIR, "clip_embeddings.h5"), "w") as f:
        f.create_dataset("embeddings", data=embeddings, dtype=np.float16)
        f.create_dataset("image_ids", data=np.array(all_image_ids, dtype=f"S{max_id_len}"))
        f.create_dataset("labels", data=labels, dtype=np.int8)

    np.save(os.path.join(OUTPUT_DIR, "clip_features.npy"), embeddings)
    np.save(os.path.join(OUTPUT_DIR, "clip_labels.npy"), labels)

    print(f"\n{'='*60}")
    print(f"  DONE! All 7 files saved to {OUTPUT_DIR}")
    print(f"  Images: {n_scored} | Real: {n_real} | Fake: {n_fake}")
    print(f"  Zero-shot acc: {zero_shot_acc:.4f} | Classifier acc: {clf_acc:.4f}")
    print(f"  Embeddings: {embeddings.shape}")
    print(f"  Time: {elapsed/60:.1f}m")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
